
export PATH=$HOME/.bin:$PATH
export PATH=/usr/local/share/npm/bin:$PATH
export PATH=/usr/local/sbin:/usr/local/bin:$PATH
export PATH=/Applications/Postgres.app/Contents/MacOS/bin:$PATH


export PATH=~/.rbenv/bin:$PATH
eval "$(rbenv init -)"

export PATH=./bin:$PATH
