
set nocompatible

filetype on
filetype plugin on
filetype indent on

syntax on

set autoread
set noswapfile
set nobackup
set nowritebackup
set nowrap

set showmode
set ruler
set number
set ch=2
set showcmd
set incsearch

set showmatch
set visualbell
set ignorecase

set autoindent
set smartindent
set virtualedit=all

" from vimcasts/e/20 for VIM in IRB
if has("autocmd")
 
  " Restore cursor position
  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif
endif


inoremap <c-f> <Right>
inoremap <c-b> <Left>
inoremap jk <Esc>

